/*==========================================================*
 *
 * @author Gustaf Franzén :: https://github.com/BjorneEk;
 * @author Adam Månsson
 *
 * instructions
 *==========================================================*/
#ifndef _INTERFACE_H_
#define _INTERFACE_H_

#define XMACRO_REGISTER(X)	\
	X(R0)	X(R1)	X(R2)	\
	X(R3)	X(R4)	X(R5)	\
	X(R6)	X(R7)	X(R8)	\
	X(R9)	X(R10)	X(R11)	\
	X(STACK_POINTER)	\
	X(PROCESSOR_STATUS)	\
	X(PROGRAM_COUNTER_L)	\
	X(PROGRAM_COUNTER_H)

enum endian_ {
	LITTLE_ENDIAN,
	BIG_ENDIAN
};

#define ADDRESS_PORTA			(0x00000001)
#define ADDRESS_DDRA			(0x00000003)
#define ADDRESS_PORTB			(0x00000005)
#define ADDRESS_DDRB			(0x00000007)
#define ADDRESS_GRAPHICS_CARD_COMM	(0x00000009)
#define ADDRESS_GRAPHICS_CARD_DATA	(0x0000000A)
#define ADDRESS_GRAPHICS_CARD_ADDRESS	(0x0000000D)

typedef enum reg_type {
	REG_R0 = 0,
	REG_R1,
	REG_R2,
	REG_R3,
	REG_R4,
	REG_R5,
	REG_R6,
	REG_R7,
	REG_R8,
	REG_R9,
	REG_R10,
	REG_R11,
	REG_STACK_POINTER,
	REG_PROCESSOR_STATUS,
	REG_PROGRAM_COUNTER_L,
	REG_PROGRAM_COUNTER_H
} reg_type_t;

#define XMACRO_ADDRESSING_MODES(X)	\
	X(IMMIDIATE)	X(REG)		\
	X(ABS)		X(ABS_PTR)	\
	X(ABS_IDX)	X(ABS_PTR_IDX)	\
	X(ABS_PTR_OFF)	X(ZP_PTR)	\
	X(ZP_OFF)	X(ZP_IDX)

#define XMACRO_DIRECT_ADDRESSING_MODES(X)	\
	X(ABS)		X(ABS_PTR)		\
	X(ABS_IDX)	X(ABS_PTR_IDX)		\
	X(ABS_PTR_OFF)	X(ZP_PTR)		\
	X(ZP_OFF)	X(ZP_IDX)

typedef enum addressing_mode {
	ADDR_MODE_RELATIVE = 0,
	ADDR_MODE_IMMIDIATE,
	ADDR_MODE_REG,
	ADDR_MODE_ABS,
	ADDR_MODE_ABS_PTR,
	ADDR_MODE_ABS_IDX,
	ADDR_MODE_ABS_PTR_IDX,
	ADDR_MODE_ABS_PTR_OFF,
	ADDR_MODE_ZP_PTR,
	ADDR_MODE_ZP_OFF,
	ADDR_MODE_ZP_IDX,
	ADDR_MODE_NULL
} addressing_mode_t;

typedef enum subinstruction_type {
	SINSTR_NOP = 0,
	SINSTR_BRK,

	SINSTR_LDR_IMMIDIATE,
	SINSTR_LDR_REG,
	SINSTR_LDR_ABS,
	SINSTR_LDR_ABS_PTR,
	SINSTR_LDR_ABS_IDX,
	SINSTR_LDR_ABS_PTR_IDX,
	SINSTR_LDR_ABS_PTR_OFF,
	SINSTR_LDR_ZP_PTR,
	SINSTR_LDR_ZP_OFF,
	SINSTR_LDR_ZP_IDX,

	SINSTR_LDRB_IMMIDIATE,
	SINSTR_LDRB_REG,
	SINSTR_LDRB_ABS,
	SINSTR_LDRB_ABS_PTR,
	SINSTR_LDRB_ABS_IDX,
	SINSTR_LDRB_ABS_PTR_IDX,
	SINSTR_LDRB_ABS_PTR_OFF,
	SINSTR_LDRB_ZP_PTR,
	SINSTR_LDRB_ZP_OFF,
	SINSTR_LDRB_ZP_IDX,

	SINSTR_LDRW_ABS,
	SINSTR_LDRW_ABS_PTR,
	SINSTR_LDRW_ABS_IDX,
	SINSTR_LDRW_ABS_PTR_IDX,
	SINSTR_LDRW_ABS_PTR_OFF,
	SINSTR_LDRW_ZP_PTR,
	SINSTR_LDRW_ZP_OFF,
	SINSTR_LDRW_ZP_IDX,

	SINSTR_STR_ABS,
	SINSTR_STR_ABS_PTR,
	SINSTR_STR_ABS_IDX,
	SINSTR_STR_ABS_PTR_IDX,
	SINSTR_STR_ABS_PTR_OFF,
	SINSTR_STR_ZP_PTR,
	SINSTR_STR_ZP_OFF,
	SINSTR_STR_ZP_IDX,

	SINSTR_STRB_ABS,
	SINSTR_STRB_ABS_PTR,
	SINSTR_STRB_ABS_IDX,
	SINSTR_STRB_ABS_PTR_IDX,
	SINSTR_STRB_ABS_PTR_OFF,
	SINSTR_STRB_ZP_PTR,
	SINSTR_STRB_ZP_OFF,
	SINSTR_STRB_ZP_IDX,

	SINSTR_CPRP,

	SINSTR_BZ,

	SINSTR_BNZ,

	SINSTR_BCC,

	SINSTR_BCS,

	SINSTR_BRN,

	SINSTR_BRP,

	SINSTR_BBS,
	SINSTR_BBC,

	SINSTR_BRA,

	SINSTR_LBRA_ABS,
	SINSTR_LBRA_ABS_PTR,

	SINSTR_CALL_ABS,
	SINSTR_CALL_ABS_PTR,
	SINSTR_CALL_ZP_PTR,

	SINSTR_RET,

	SINSTR_RTI,

	SINSTR_ADC_IMMIDIATE,
	SINSTR_ADC_REG,
	SINSTR_ADC_ABS,
	SINSTR_ADC_ABS_PTR,
	SINSTR_ADC_ABS_IDX,
	SINSTR_ADC_ABS_PTR_IDX,
	SINSTR_ADC_ABS_PTR_OFF,
	SINSTR_ADC_ZP_PTR,
	SINSTR_ADC_ZP_OFF,
	SINSTR_ADC_ZP_IDX,

	SINSTR_ADD_IMMIDIATE,
	SINSTR_ADD_REG,
	SINSTR_ADD_ABS,
	SINSTR_ADD_ABS_PTR,
	SINSTR_ADD_ABS_IDX,
	SINSTR_ADD_ABS_PTR_IDX,
	SINSTR_ADD_ABS_PTR_OFF,
	SINSTR_ADD_ZP_PTR,
	SINSTR_ADD_ZP_OFF,
	SINSTR_ADD_ZP_IDX,

	SINSTR_ADCW_IMMIDIATE,
	SINSTR_ADCW_REG,
	SINSTR_ADCW_ABS,
	SINSTR_ADCW_ABS_PTR,
	SINSTR_ADCW_ABS_IDX,
	SINSTR_ADCW_ABS_PTR_IDX,
	SINSTR_ADCW_ABS_PTR_OFF,
	SINSTR_ADCW_ZP_PTR,
	SINSTR_ADCW_ZP_OFF,
	SINSTR_ADCW_ZP_IDX,

	SINSTR_ADDW_IMMIDIATE,
	SINSTR_ADDW_REG,
	SINSTR_ADDW_ABS,
	SINSTR_ADDW_ABS_PTR,
	SINSTR_ADDW_ABS_IDX,
	SINSTR_ADDW_ABS_PTR_IDX,
	SINSTR_ADDW_ABS_PTR_OFF,
	SINSTR_ADDW_ZP_PTR,
	SINSTR_ADDW_ZP_OFF,
	SINSTR_ADDW_ZP_IDX,

	SINSTR_SBC_IMMIDIATE,
	SINSTR_SBC_REG,
	SINSTR_SBC_ABS,
	SINSTR_SBC_ABS_PTR,
	SINSTR_SBC_ABS_IDX,
	SINSTR_SBC_ABS_PTR_IDX,
	SINSTR_SBC_ABS_PTR_OFF,
	SINSTR_SBC_ZP_PTR,
	SINSTR_SBC_ZP_OFF,
	SINSTR_SBC_ZP_IDX,

	SINSTR_SUB_IMMIDIATE,
	SINSTR_SUB_REG,
	SINSTR_SUB_ABS,
	SINSTR_SUB_ABS_PTR,
	SINSTR_SUB_ABS_IDX,
	SINSTR_SUB_ABS_PTR_IDX,
	SINSTR_SUB_ABS_PTR_OFF,
	SINSTR_SUB_ZP_PTR,
	SINSTR_SUB_ZP_OFF,
	SINSTR_SUB_ZP_IDX,

	SINSTR_SBCW_IMMIDIATE,
	SINSTR_SBCW_REG,
	SINSTR_SBCW_ABS,
	SINSTR_SBCW_ABS_PTR,
	SINSTR_SBCW_ABS_IDX,
	SINSTR_SBCW_ABS_PTR_IDX,
	SINSTR_SBCW_ABS_PTR_OFF,
	SINSTR_SBCW_ZP_PTR,
	SINSTR_SBCW_ZP_OFF,
	SINSTR_SBCW_ZP_IDX,

	SINSTR_SUBW_IMMIDIATE,
	SINSTR_SUBW_REG,
	SINSTR_SUBW_ABS,
	SINSTR_SUBW_ABS_PTR,
	SINSTR_SUBW_ABS_IDX,
	SINSTR_SUBW_ABS_PTR_IDX,
	SINSTR_SUBW_ABS_PTR_OFF,
	SINSTR_SUBW_ZP_PTR,
	SINSTR_SUBW_ZP_OFF,
	SINSTR_SUBW_ZP_IDX,

	SINSTR_EOR_IMMIDIATE,
	SINSTR_EOR_REG,
	SINSTR_EOR_ABS,
	SINSTR_EOR_ABS_PTR,
	SINSTR_EOR_ABS_IDX,
	SINSTR_EOR_ABS_PTR_IDX,
	SINSTR_EOR_ABS_PTR_OFF,
	SINSTR_EOR_ZP_PTR,
	SINSTR_EOR_ZP_OFF,
	SINSTR_EOR_ZP_IDX,

	SINSTR_ORR_IMMIDIATE,
	SINSTR_ORR_REG,
	SINSTR_ORR_ABS,
	SINSTR_ORR_ABS_PTR,
	SINSTR_ORR_ABS_IDX,
	SINSTR_ORR_ABS_PTR_IDX,
	SINSTR_ORR_ABS_PTR_OFF,
	SINSTR_ORR_ZP_PTR,
	SINSTR_ORR_ZP_OFF,
	SINSTR_ORR_ZP_IDX,

	SINSTR_AND_IMMIDIATE,
	SINSTR_AND_REG,
	SINSTR_AND_ABS,
	SINSTR_AND_ABS_PTR,
	SINSTR_AND_ABS_IDX,
	SINSTR_AND_ABS_PTR_IDX,
	SINSTR_AND_ABS_PTR_OFF,
	SINSTR_AND_ZP_PTR,
	SINSTR_AND_ZP_OFF,
	SINSTR_AND_ZP_IDX,

	SINSTR_CMP_IMMIDIATE,
	SINSTR_CMP_REG,
	SINSTR_CMP_ABS,
	SINSTR_CMP_ABS_PTR,
	SINSTR_CMP_ABS_IDX,
	SINSTR_CMP_ABS_PTR_IDX,
	SINSTR_CMP_ABS_PTR_OFF,
	SINSTR_CMP_ZP_PTR,
	SINSTR_CMP_ZP_OFF,
	SINSTR_CMP_ZP_IDX,

	SINSTR_ASR,

	SINSTR_LSR,

	SINSTR_LSL,

	SINSTR_NOT,

	SINSTR_DEC,

	SINSTR_DECW,

	SINSTR_INC,

	SINSTR_INCW,

	SINSTR_CRB_IMMIDIATE,
	SINSTR_CRB_REG,
	SINSTR_CRB_ABS,
	SINSTR_CRB_ABS_PTR,
	SINSTR_CRB_ABS_IDX,
	SINSTR_CRB_ABS_PTR_IDX,
	SINSTR_CRB_ABS_PTR_OFF,
	SINSTR_CRB_ZP_PTR,
	SINSTR_CRB_ZP_OFF,
	SINSTR_CRB_ZP_IDX,

	SINSTR_SRB_IMMIDIATE,
	SINSTR_SRB_REG,
	SINSTR_SRB_ABS,
	SINSTR_SRB_ABS_PTR,
	SINSTR_SRB_ABS_IDX,
	SINSTR_SRB_ABS_PTR_IDX,
	SINSTR_SRB_ABS_PTR_OFF,
	SINSTR_SRB_ZP_PTR,
	SINSTR_SRB_ZP_OFF,
	SINSTR_SRB_ZP_IDX,

	SINSTR_NULL	// used to extend enum
} subinstruction_type_t;

#define XMACRO_SUBINSTRUCTIONS(X)	\
	X(NOP)			\
	X(BRK)			\
	X(LDR_IMMIDIATE)	\
	X(LDR_REG)		\
	X(LDR_ABS)		\
	X(LDR_ABS_PTR)		\
	X(LDR_ABS_IDX)		\
	X(LDR_ABS_PTR_IDX)	\
	X(LDR_ABS_PTR_OFF)	\
	X(LDR_ZP_PTR)		\
	X(LDR_ZP_OFF)		\
	X(LDR_ZP_IDX)		\
	X(LDRB_IMMIDIATE)	\
	X(LDRB_REG)		\
	X(LDRB_ABS)		\
	X(LDRB_ABS_PTR)		\
	X(LDRB_ABS_IDX)		\
	X(LDRB_ABS_PTR_IDX)	\
	X(LDRB_ABS_PTR_OFF)	\
	X(LDRB_ZP_PTR)		\
	X(LDRB_ZP_OFF)		\
	X(LDRB_ZP_IDX)		\
	X(LDRW_ABS)		\
	X(LDRW_ABS_PTR)		\
	X(LDRW_ABS_IDX)		\
	X(LDRW_ABS_PTR_IDX)	\
	X(LDRW_ABS_PTR_OFF)	\
	X(LDRW_ZP_PTR)		\
	X(LDRW_ZP_OFF)		\
	X(LDRW_ZP_IDX)		\
	X(STR_ABS)		\
	X(STR_ABS_PTR)		\
	X(STR_ABS_IDX)		\
	X(STR_ABS_PTR_IDX)	\
	X(STR_ABS_PTR_OFF)	\
	X(STR_ZP_PTR)		\
	X(STR_ZP_OFF)		\
	X(STR_ZP_IDX)		\
	X(STRB_ABS)		\
	X(STRB_ABS_PTR)		\
	X(STRB_ABS_IDX)		\
	X(STRB_ABS_PTR_IDX)	\
	X(STRB_ABS_PTR_OFF)	\
	X(STRB_ZP_PTR)		\
	X(STRB_ZP_OFF)		\
	X(STRB_ZP_IDX)		\
	X(CPRP)			\
	X(BZ)			\
	X(BNZ)			\
	X(BCC)			\
	X(BCS)			\
	X(BRN)			\
	X(BRP)			\
	X(BBS)			\
	X(BBC)			\
	X(BRA)			\
	X(LBRA_ABS)		\
	X(LBRA_ABS_PTR)		\
	X(CALL_ABS)		\
	X(CALL_ABS_PTR)		\
	X(CALL_ZP_PTR)		\
	X(RET)			\
	X(RTI)			\
	X(ADC_IMMIDIATE)	\
	X(ADC_REG)		\
	X(ADC_ABS)		\
	X(ADC_ABS_PTR)		\
	X(ADC_ABS_IDX)		\
	X(ADC_ABS_PTR_IDX)	\
	X(ADC_ABS_PTR_OFF)	\
	X(ADC_ZP_PTR)		\
	X(ADC_ZP_OFF)		\
	X(ADC_ZP_IDX)		\
	X(ADD_IMMIDIATE)	\
	X(ADD_REG)		\
	X(ADD_ABS)		\
	X(ADD_ABS_PTR)		\
	X(ADD_ABS_IDX)		\
	X(ADD_ABS_PTR_IDX)	\
	X(ADD_ABS_PTR_OFF)	\
	X(ADD_ZP_PTR)		\
	X(ADD_ZP_OFF)		\
	X(ADD_ZP_IDX)		\
	X(ADCW_IMMIDIATE)	\
	X(ADCW_REG)		\
	X(ADCW_ABS)		\
	X(ADCW_ABS_PTR)		\
	X(ADCW_ABS_IDX)		\
	X(ADCW_ABS_PTR_IDX)	\
	X(ADCW_ABS_PTR_OFF)	\
	X(ADCW_ZP_PTR)		\
	X(ADCW_ZP_OFF)		\
	X(ADCW_ZP_IDX)		\
	X(ADDW_IMMIDIATE)	\
	X(ADDW_REG)		\
	X(ADDW_ABS)		\
	X(ADDW_ABS_PTR)		\
	X(ADDW_ABS_IDX)		\
	X(ADDW_ABS_PTR_IDX)	\
	X(ADDW_ABS_PTR_OFF)	\
	X(ADDW_ZP_PTR)		\
	X(ADDW_ZP_OFF)		\
	X(ADDW_ZP_IDX)		\
	X(SBC_IMMIDIATE)	\
	X(SBC_REG)		\
	X(SBC_ABS)		\
	X(SBC_ABS_PTR)		\
	X(SBC_ABS_IDX)		\
	X(SBC_ABS_PTR_IDX)	\
	X(SBC_ABS_PTR_OFF)	\
	X(SBC_ZP_PTR)		\
	X(SBC_ZP_OFF)		\
	X(SBC_ZP_IDX)		\
	X(SUB_IMMIDIATE)	\
	X(SUB_REG)		\
	X(SUB_ABS)		\
	X(SUB_ABS_PTR)		\
	X(SUB_ABS_IDX)		\
	X(SUB_ABS_PTR_IDX)	\
	X(SUB_ABS_PTR_OFF)	\
	X(SUB_ZP_PTR)		\
	X(SUB_ZP_OFF)		\
	X(SUB_ZP_IDX)		\
	X(SBCW_IMMIDIATE)	\
	X(SBCW_REG)		\
	X(SBCW_ABS)		\
	X(SBCW_ABS_PTR)		\
	X(SBCW_ABS_IDX)		\
	X(SBCW_ABS_PTR_IDX)	\
	X(SBCW_ABS_PTR_OFF)	\
	X(SBCW_ZP_PTR)		\
	X(SBCW_ZP_OFF)		\
	X(SBCW_ZP_IDX)		\
	X(SUBW_IMMIDIATE)	\
	X(SUBW_REG)		\
	X(SUBW_ABS)		\
	X(SUBW_ABS_PTR)		\
	X(SUBW_ABS_IDX)		\
	X(SUBW_ABS_PTR_IDX)	\
	X(SUBW_ABS_PTR_OFF)	\
	X(SUBW_ZP_PTR)		\
	X(SUBW_ZP_OFF)		\
	X(SUBW_ZP_IDX)		\
	X(EOR_IMMIDIATE)	\
	X(EOR_REG)		\
	X(EOR_ABS)		\
	X(EOR_ABS_PTR)		\
	X(EOR_ABS_IDX)		\
	X(EOR_ABS_PTR_IDX)	\
	X(EOR_ABS_PTR_OFF)	\
	X(EOR_ZP_PTR)		\
	X(EOR_ZP_OFF)		\
	X(EOR_ZP_IDX)		\
	X(ORR_IMMIDIATE)	\
	X(ORR_REG)		\
	X(ORR_ABS)		\
	X(ORR_ABS_PTR)		\
	X(ORR_ABS_IDX)		\
	X(ORR_ABS_PTR_IDX)	\
	X(ORR_ABS_PTR_OFF)	\
	X(ORR_ZP_PTR)		\
	X(ORR_ZP_OFF)		\
	X(ORR_ZP_IDX)		\
	X(AND_IMMIDIATE)	\
	X(AND_REG)		\
	X(AND_ABS)		\
	X(AND_ABS_PTR)		\
	X(AND_ABS_IDX)		\
	X(AND_ABS_PTR_IDX)	\
	X(AND_ABS_PTR_OFF)	\
	X(AND_ZP_PTR)		\
	X(AND_ZP_OFF)		\
	X(AND_ZP_IDX)		\
	X(CMP_IMMIDIATE)	\
	X(CMP_REG)		\
	X(CMP_ABS)		\
	X(CMP_ABS_PTR)		\
	X(CMP_ABS_IDX)		\
	X(CMP_ABS_PTR_IDX)	\
	X(CMP_ABS_PTR_OFF)	\
	X(CMP_ZP_PTR)		\
	X(CMP_ZP_OFF)		\
	X(CMP_ZP_IDX)		\
	X(ASR)			\
	X(LSR)			\
	X(LSL)			\
	X(NOT)			\
	X(DEC)			\
	X(DECW)			\
	X(INC)			\
	X(INCW)			\
	X(CRB_IMMIDIATE)	\
	X(CRB_REG)		\
	X(CRB_ABS)		\
	X(CRB_ABS_PTR)		\
	X(CRB_ABS_IDX)		\
	X(CRB_ABS_PTR_IDX)	\
	X(CRB_ABS_PTR_OFF)	\
	X(CRB_ZP_PTR)		\
	X(CRB_ZP_OFF)		\
	X(CRB_ZP_IDX)		\
	X(SRB_IMMIDIATE)	\
	X(SRB_REG)		\
	X(SRB_ABS)		\
	X(SRB_ABS_PTR)		\
	X(SRB_ABS_IDX)		\
	X(SRB_ABS_PTR_IDX)	\
	X(SRB_ABS_PTR_OFF)	\
	X(SRB_ZP_PTR)		\
	X(SRB_ZP_OFF)		\
	X(SRB_ZP_IDX)

#define XMACRO_INSTRUCTIONS(X)	\
	X(NOP)	X(BRK)	X(LDR)	\
	X(LDRB)	X(LDRW)	X(STR)	\
	X(STRB)	X(CPRP)		\
	X(BZ)	X(BNZ)	X(BCC)	\
	X(BCS)	X(BRN)	X(BRP)	\
	X(BBS)	X(BBC)	X(BRA)	\
	X(LBRA)	X(CALL)	X(RET)	\
	X(RTI)	X(ADC)	X(ADD)	\
	X(ADCW)	X(ADDW)	X(SBC)	\
	X(SUB)	X(SBCW)	X(SUBW)	\
	X(EOR)	X(ORR)	X(AND)	\
	X(CMP)	X(ASR)	X(LSL)	\
	X(LSR)	X(NOT)	X(DEC)	\
	X(DECW)	X(INC)	X(INCW)	\
	X(CRB)	X(SRB)

typedef enum instruction_type {
	INSTR_NOP	=	SINSTR_NOP,
	INSTR_BRK	=	SINSTR_BRK,
	INSTR_LDR	=	SINSTR_LDR_IMMIDIATE,
	INSTR_LDRB	=	SINSTR_LDRB_IMMIDIATE,
	INSTR_LDRW	=	SINSTR_LDRW_ABS,
	INSTR_STR	=	SINSTR_STR_ABS,
	INSTR_STRB	=	SINSTR_STRB_ABS,
	INSTR_CPRP	=	SINSTR_CPRP,
	INSTR_BZ	=	SINSTR_BZ,
	INSTR_BNZ	=	SINSTR_BNZ,
	INSTR_BCC	=	SINSTR_BCC,
	INSTR_BCS	=	SINSTR_BCS,
	INSTR_BRN	=	SINSTR_BRN,
	INSTR_BRP	=	SINSTR_BRP,
	INSTR_BBS	=	SINSTR_BBS,
	INSTR_BBC	=	SINSTR_BBC,
	INSTR_BRA	=	SINSTR_BRA,
	INSTR_LBRA	=	SINSTR_LBRA_ABS,
	INSTR_CALL	=	SINSTR_CALL_ABS,
	INSTR_RET	=	SINSTR_RET,
	INSTR_RTI	=	SINSTR_RTI,
	INSTR_ADC	=	SINSTR_ADC_IMMIDIATE,
	INSTR_ADD	=	SINSTR_ADD_IMMIDIATE,
	INSTR_ADCW	=	SINSTR_ADCW_IMMIDIATE,
	INSTR_ADDW	=	SINSTR_ADDW_IMMIDIATE,
	INSTR_SBC	=	SINSTR_SBC_IMMIDIATE,
	INSTR_SUB	=	SINSTR_SUB_IMMIDIATE,
	INSTR_SBCW	=	SINSTR_SBCW_IMMIDIATE,
	INSTR_SUBW	=	SINSTR_SUBW_IMMIDIATE,
	INSTR_EOR	=	SINSTR_EOR_IMMIDIATE,
	INSTR_ORR	=	SINSTR_ORR_IMMIDIATE,
	INSTR_AND	=	SINSTR_AND_IMMIDIATE,
	INSTR_CMP	=	SINSTR_CMP_IMMIDIATE,
	INSTR_ASR	=	SINSTR_ASR,
	INSTR_LSL	=	SINSTR_LSL,
	INSTR_LSR	=	SINSTR_LSR,
	INSTR_NOT	=	SINSTR_NOT,
	INSTR_DEC	=	SINSTR_DEC,
	INSTR_DECW	=	SINSTR_DECW,
	INSTR_INC	=	SINSTR_INC,
	INSTR_INCW	=	SINSTR_INCW,
	INSTR_CRB	=	SINSTR_CRB_IMMIDIATE,
	INSTR_SRB	=	SINSTR_SRB_IMMIDIATE,

	INSTR_NULL	// used to extend enum
} instruction_type_t;

extern const int addressing_mode_size[ADDR_MODE_NULL];
extern const int instruction_size[INSTR_NULL];
extern const int supported_addressing_modes[INSTR_NULL][ADDR_MODE_NULL];
extern const int endian;

void print_sinstr(int sinstr);

#endif /* _INTERFACE_H_ */